In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('df_bp1.csv')

C:\Users\sanch\AppData\Local\Temp\ipykernel_10212\2649927610.py:1: DtypeWarning: Columns (13,14,15,85,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_bp1.csv')

In [35]:
df.columns

Index(['date', 'dblheader_code', 'day_of_week', 'team_v', 'league_v',
       'game_no_v', 'team_h', 'league_h', 'game_no_h', 'runs_v',
       ...
       'SLG_30_h', 'SLG_30_v', 'OBS_30_h', 'OBS_30_v', 'SB_30_h', 'SB_30_v',
       'CS_30_h', 'CS_30_v', 'ERR_30_h', 'ERR_30_v'],
      dtype='object', length=194)

In [33]:
df.head(40)

,date,dblheader_code,day_of_week,team_v,league_v,game_no_v,team_h,league_h,game_no_h,runs_v,...,SLG_30_h,SLG_30_v,OBS_30_h,OBS_30_v,SB_30_h,SB_30_v,CS_30_h,CS_30_v,ERR_30_h,ERR_30_v
2245,19950616,0,Fri,SFN,NL,48,SLN,NL,48,5,...,0.388074,0.374275,0.708254,0.673735,16.0,33.0,8.0,12.0,22.0,28.0
2259,19950617,0,Sat,SFN,NL,49,SLN,NL,49,4,...,0.390148,0.378378,0.712028,0.680975,17.0,33.0,7.0,12.0,24.0,28.0
2268,19950618,0,Sun,MON,NL,50,CIN,NL,48,7,...,0.436941,0.387695,0.785737,0.712428,46.0,27.0,11.0,10.0,18.0,17.0
2269,19950618,0,Sun,ATL,NL,49,COL,NL,49,9,...,0.458984,0.440276,0.796798,0.779244,23.0,16.0,16.0,11.0,22.0,19.0
2271,19950618,0,Sun,FLO,NL,48,PHI,NL,48,3,...,0.355131,0.373412,0.690266,0.694399,11.0,16.0,7.0,12.0,23.0,21.0
2273,19950618,0,Sun,SFN,NL,50,SLN,NL,50,6,...,0.380811,0.388088,0.699941,0.693718,18.0,33.0,7.0,13.0,24.0,27.0
2275,19950619,0,Mon,KCA,AL,48,CAL,AL,50,8,...,0.470701,0.406489,0.841354,0.746987,13.0,33.0,14.0,15.0,15.0,18.0
2278,19950619,0,Mon,TEX,AL,50,DET,AL,51,6,...,0.442289,0.404150,0.799069,0.756413,25.0,25.0,9.0,12.0,25.0,17.0
2279,19950619,0,Mon,MIN,AL,50,OAK,AL,51,8,...,0.399608,0.426372,0.728567,0.756745,26.0,16.0,13.0,10.0,25.0,16.0
2280,19950619,0,Mon,ATL,NL,50,CIN,NL,49,10,...,0.445879,0.441406,0.800546,0.780045,49.0,16.0,11.0,11.0,16.0,20.0
2281,19950619,0,Mon,FLO,NL,49,COL,NL,50,7,...,0.460938,0.379648,0.799344,0.697628,23.0,16.0,16.0,11.0,22.0,21.0
2282,19950619,0,Mon,HOU,NL,48,MON,NL,51,6,...,0.375610,0.371807,0.698563,0.691011,27.0,35.0,10.0,15.0,17.0,22.0
2283,19950619,0,Mon,PHI,NL,49,NYN,NL,50,6,...,0.377127,0.363819,0.698029,0.701353,13.0,10.0,6.0,7.0,26.0,22.0
2286,19950619,0,Mon,LAN,NL,50,SLN,NL,51,5,...,0.381944,0.387560,0.701035,0.711244,17.0,17.0,7.0,12.0,26.0,19.0
2288,19950620,0,Tue,KCA,AL,49,CAL,AL,51,2,...,0.466475,0.415005,0.836814,0.758033,13.0,35.0,14.0,15.0,13.0,18.0
2291,19950620,0,Tue,TEX,AL,51,DET,AL,52,8,...,0.449275,0.399408,0.807686,0.748122,26.0,25.0,8.0,12.0,26.0,16.0
2292,19950620,0,Tue,MIN,AL,51,OAK,AL,52,2,...,0.399417,0.425287,0.731594,0.754793,28.0,15.0,13.0,10.0,23.0,16.0
2294,19950620,0,Tue,ATL,NL,51,CIN,NL,50,10,...,0.436690,0.425197,0.786422,0.759122,48.0,16.0,12.0,11.0,17.0,20.0
2295,19950620,0,Tue,FLO,NL,50,COL,NL,51,7,...,0.472656,0.376459,0.816992,0.691552,21.0,17.0,16.0,10.0,24.0,21.0
2296,19950620,0,Tue,HOU,NL,49,MON,NL,52,7,...,0.376953,0.378531,0.701085,0.700083,27.0,40.0,10.0,17.0,19.0,21.0
2297,19950620,0,Tue,PHI,NL,50,NYN,NL,51,8,...,0.377251,0.367677,0.698121,0.702219,13.0,12.0,6.0,7.0,27.0,20.0
2298,19950620,0,Tue,SFN,NL,52,PIT,NL,49,3,...,0.408955,0.405894,0.731389,0.720938,20.0,35.0,16.0,13.0,27.0,29.0
2299,19950620,0,Tue,CHN,NL,50,SDN,NL,50,7,...,0.385913,0.400976,0.692689,0.691652,26.0,17.0,9.0,6.0,22.0,17.0
2300,19950620,0,Tue,LAN,NL,51,SLN,NL,52,0,...,0.376740,0.393097,0.692481,0.717635,15.0,18.0,7.0,12.0,27.0,20.0
2302,19950621,0,Wed,KCA,AL,50,CAL,AL,52,6,...,0.451208,0.402132,0.815156,0.736926,13.0,37.0,14.0,14.0,13.0,19.0
2304,19950621,0,Wed,BOS,AL,50,CLE,AL,50,3,...,0.523810,0.434411,0.897036,0.781454,29.0,21.0,15.0,12.0,29.0,23.0
2305,19950621,0,Wed,TEX,AL,52,DET,AL,53,0,...,0.450772,0.394659,0.807250,0.738353,25.0,26.0,8.0,12.0,26.0,18.0
2306,19950621,0,Wed,MIN,AL,52,OAK,AL,53,3,...,0.400588,0.418112,0.728959,0.747304,25.0,16.0,14.0,9.0,23.0,17.0
2307,19950621,0,Wed,MIL,AL,49,TOR,AL,48,10,...,0.408423,0.412713,0.736117,0.742811,12.0,30.0,3.0,7.0,19.0,19.0
2308,19950621,0,Wed,ATL,NL,52,CIN,NL,51,1,...,0.436508,0.429268,0.787042,0.769937,48.0,16.0,12.0,11.0,18.0,19.0
2309,19950621,0,Wed,FLO,NL,51,COL,NL,52,3,...,0.469608,0.381463,0.812184,0.694631,20.0,17.0,18.0,9.0,24.0,18.0
2310,19950621,0,Wed,HOU,NL,50,MON,NL,53,5,...,0.384241,0.377111,0.712546,0.698141,25.0,38.0,10.0,16.0,20.0,20.0
2311,19950621,0,Wed,PHI,NL,51,NYN,NL,52,6,...,0.370124,0.374115,0.687389,0.713824,13.0,13.0,6.0,6.0,27.0,22.0
2312,19950621,0,Wed,SFN,NL,53,PIT,NL,50,6,...,0.415675,0.411597,0.739631,0.729015,20.0,36.0,17.0,12.0,26.0,27.0
2313,19950621,0,Wed,CHN,NL,51,SDN,NL,51,0,...,0.385982,0.397661,0.695354,0.687688,26.0,16.0,9.0,7.0,23.0,17.0
2314,19950621,0,Wed,LAN,NL,52,SLN,NL,53,10,...,0.382470,0.386473,0.702434,0.706473,15.0,18.0,7.0,13.0,27.0,21.0
2315,19950622,0,Thu,BOS,AL,51,BAL,AL,51,4,...,0.440233,0.437859,0.764051,0.781581,28.0,22.0,11.0,13.0,17.0,23.0
2317,19950622,0,Thu,MIL,AL,50,TOR,AL,49,9,...,0.416016,0.420057,0.746396,0.755140,13.0,33.0,3.0,7.0,20.0,19.0
2318,19950622,0,Thu,ATL,NL,53,CIN,NL,52,8,...,0.426148,0.424658,0.763693,0.762984,48.0,15.0,11.0,11.0,18.0,18.0
2319,19950622,0,Thu,CHN,NL,52,HOU,NL,51,13,...,0.380730,0.390244,0.703780,0.674251,40.0,15.0,17.0,7.0,20.0,17.0

In [5]:
df.info(max_cols=200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67355 entries, 0 to 67354
Data columns (total 194 columns):
 #    Column                Non-Null Count  Dtype
---   ------                --------------  -----
 0    date                  67355 non-null  int64
 1    dblheader_code        67355 non-null  int64
 2    day_of_week           67355 non-null  object
 3    team_v                67355 non-null  object
 4    league_v              67355 non-null  object
 5    game_no_v             67355 non-null  int64
 6    team_h                67355 non-null  object
 7    league_h              67355 non-null  object
 8    game_no_h             67355 non-null  int64
 9    runs_v                67355 non-null  int64
 10   runs_h                67355 non-null  int64
 11   outs_total            67355 non-null  int64
 12   day_night             67355 non-null  object
 13   completion_info       54 non-null     object
 14   forfeit_info          1 non-null      object
 15   protest_info          28 non-null     object
 16   ballpark_id           67355 non-null  object
 17   attendance            66455 non-null  float64
 18   game_minutes          67355 non-null  int64
 19   linescore_v           67355 non-null  object
 20   linescore_h           67355 non-null  object
 21   AB_v                  67355 non-null  int64
 22   H_v                   67355 non-null  int64
 23   2B_v                  67355 non-null  int64
 24   3B_v                  67355 non-null  int64
 25   HR_v                  67355 non-null  int64
 26   RBI_v                 67355 non-null  int64
 27   SH_v                  67355 non-null  int64
 28   SF_v                  67355 non-null  int64
 29   HBP_v                 67355 non-null  int64
 30   BB_v                  67355 non-null  int64
 31   IBB_v                 67355 non-null  int64
 32   SO_v                  67355 non-null  int64
 33   SB_v                  67355 non-null  int64
 34   CS_v                  67355 non-null  int64
 35   GIDP_v                67355 non-null  int64
 36   CI_v                  67355 non-null  int64
 37   LOB_v                 67355 non-null  int64
 38   P_num_v               67355 non-null  int64
 39   ERind_v               67355 non-null  int64
 40   ERteam_v              67355 non-null  int64
 41   WP_v                  67355 non-null  int64
 42   balk_v                67355 non-null  int64
 43   PO_v                  67355 non-null  int64
 44   ASST_v                67355 non-null  int64
 45   ERR_v                 67355 non-null  int64
 46   PB_v                  67355 non-null  int64
 47   DP_v                  67355 non-null  int64
 48   TP_v                  67355 non-null  int64
 49   AB_h                  67355 non-null  int64
 50   H_h                   67355 non-null  int64
 51   2B_h                  67355 non-null  int64
 52   3B_h                  67355 non-null  int64
 53   HR_h                  67355 non-null  int64
 54   RBI_h                 67355 non-null  int64
 55   SH_h                  67355 non-null  int64
 56   SF_h                  67355 non-null  int64
 57   HBP_h                 67355 non-null  int64
 58   BB_h                  67355 non-null  int64
 59   IBB_h                 67355 non-null  int64
 60   SO_h                  67355 non-null  int64
 61   SB_h                  67355 non-null  int64
 62   CS_h                  67355 non-null  int64
 63   GIDP_h                67355 non-null  int64
 64   CI_h                  67355 non-null  int64
 65   LOB_h                 67355 non-null  int64
 66   P_num_h               67355 non-null  int64
 67   ERind_h               67355 non-null  int64
 68   ERteam_h              67355 non-null  int64
 69   WP_h                  67355 non-null  int64
 70   balk_h                67355 non-null  int64
 71   PO_h                  67355 non-null  int64
 72   ASST_h                67355 non-null  int64
 73   ERR_h                 67355 non-null  int64
 74   PB_h                  67355 non-null  int64
 75   DP_h                  67355 non-null  int64
 76   TP_h                  67355 non-null  int64
 77   ump_HB_id             67355 non-null  object
 78   ump_HB_name           67355 non-null  object
 79   ump_1B_id             67355 non-null  object
 80   ump_1B_name           67355 non-null  object
 81   ump_2B_id             67183 non-null  object
 82   ump_2B_name           67355 non-null  object
 83   ump_3B_id             67354 non-null  object
 84   ump_3B_name           67355 non-null  object
 85   ump_LF_id             9 non-null      object
 86   ump_LF_name           67355 non-null  object
 87   ump_RF_id             9 non-null      object
 88   ump_RF_name           67355 non-null  object
 89   mgr_id_v              67355 non-null  object
 90   mgr_name_v            67355 non-null  object
 91   mgr_id_h              67355 non-null  object
 92   mgr_name_h            67355 non-null  object
 93   pitcher_id_w          67343 non-null  object
 94   pitcher_name_w        67343 non-null  object
 95   pitcher_id_l          67343 non-null  object
 96   pitcher_name_l        67343 non-null  object
 97   pitcher_id_s          33853 non-null  object
 98   pitcher_name_s        67355 non-null  object
 99   GWRBI_id              64075 non-null  object
 100  GWRBI_name            67355 non-null  object
 101  pitcher_start_id_v    67355 non-null  object
 102  pitcher_start_name_v  67355 non-null  object
 103  pitcher_start_id_h    67355 non-null  object
 104  pitcher_start_name_h  67355 non-null  object
 105  batter1_name_v        67355 non-null  object
 106  batter1_id_v          67355 non-null  object
 107  batter1_pos_v         67355 non-null  int64
 108  batter2_name_v        67355 non-null  object
 109  batter2_id_v          67355 non-null  object
 110  batter2_pos_v         67355 non-null  int64
 111  batter3_name_v        67355 non-null  object
 112  batter3_id_v          67355 non-null  object
 113  batter3_pos_v         67355 non-null  int64
 114  batter4_name_v        67355 non-null  object
 115  batter4_id_v          67355 non-null  object
 116  batter4_pos_v         67355 non-null  int64
 117  batter5_name_v        67355 non-null  object
 118  batter5_id_v          67355 non-null  object
 119  batter5_pos_v         67355 non-null  int64
 120  batter6_name_v        67355 non-null  object
 121  batter6_id_v          67355 non-null  object
 122  batter6_pos_v         67355 non-null  int64
 123  batter7_name_v        67355 non-null  object
 124  batter7_id_v          67355 non-null  object
 125  batter7_pos_v         67355 non-null  int64
 126  batter8_name_v        67355 non-null  object
 127  batter8_id_v          67355 non-null  object
 128  batter8_pos_v         67355 non-null  int64
 129  batter9_name_v        67355 non-null  object
 130  batter9_id_v          67355 non-null  object
 131  batter9_pos_v         67355 non-null  int64
 132  batter1_name_h        67355 non-null  object
 133  batter1_id_h          67355 non-null  object
 134  batter1_pos_h         67355 non-null  int64
 135  batter2_name_h        67355 non-null  object
 136  batter2_id_h          67355 non-null  object
 137  batter2_pos_h         67355 non-null  int64
 138  batter3_name_h        67355 non-null  object
 139  batter3_id_h          67355 non-null  object
 140  batter3_pos_h         67355 non-null  int64
 141  batter4_name_h        67355 non-null  object
 142  batter4_id_h          67355 non-null  object
 143  batter4_pos_h         67355 non-null  int64
 144  batter5_name_h        67355 non-null  object
 145  batter5_id_h          67355 non-null  object
 146  batter5_pos_h         67355 non-null  int64
 147  batter6_name_h        67355 non-null  object
 148  batter6_id_h          67355 non-null  object
 149  batter6_pos_h         67355 non-null  int64
 150  batter7_name_h        67355 non-null  object
 151  batter7_id_h          67355 non-null  object
 152  batter7_pos_h         67355 non-null  int64
 153  batter8_name_h        67355 non-null  object
 154  batter8_id_h          67355 non-null  object
 155  batter8_pos_h         67355 non-null  int64
 156  batter9_name_h        67355 non-null  object
 157  batter9_id_h          67355 non-null  object
 158  batter9_pos_h         67355 non-null  int64
 159  misc_info             332 non-null    object
 160  acqui_info            67355 non-null  object
 161  season                67355 non-null  int64
 162  run_diff              67355 non-null  int64
 163  home_victory          67355 non-null  int64
 164  run_total             67355 non-null  int64
 165  date_dblhead          67355 non-null  int64
 166  BATAVG_162_h          64680 non-null  float64
 167  BATAVG_162_v          64684 non-null  float64
 168  OBP_162_h             64680 non-null  float64
 169  OBP_162_v             64684 non-null  float64
 170  SLG_162_h             64680 non-null  float64
 171  SLG_162_v             64684 non-null  float64
 172  OBS_162_h             64680 non-null  float64
 173  OBS_162_v             64684 non-null  float64
 174  SB_162_h              64680 non-null  float64
 175  SB_162_v              64684 non-null  float64
 176  CS_162_h              64680 non-null  float64
 177  CS_162_v              64684 non-null  float64
 178  ERR_162_h             64680 non-null  float64
 179  ERR_162_v             64684 non-null  float64
 180  BATAVG_30_h           66873 non-null  float64
 181  BATAVG_30_v           66847 non-null  float64
 182  OBP_30_h              66873 non-null  float64
 183  OBP_30_v              66847 non-null  float64
 184  SLG_30_h              66873 non-null  float64
 185  SLG_30_v              66847 non-null  float64
 186  OBS_30_h              66873 non-null  float64
 187  OBS_30_v              66847 non-null  float64
 188  SB_30_h               66873 non-null  float64
 189  SB_30_v               66847 non-null  float64
 190  CS_30_h               66873 non-null  float64
 191  CS_30_v               66847 non-null  float64
 192  ERR_30_h              66873 non-null  float64
 193  ERR_30_v              66847 non-null  float64
dtypes: float64(29), int64(87), object(78)
memory usage: 99.7+ MB

In [6]:
df.season.value_counts().sort_index()

1994    1600
1995    2017
1996    2267
1997    2266
1998    2432
1999    2428
2000    2429
2001    2429
2002    2426
2003    2430
2004    2428
2005    2431
2006    2429
2007    2431
2008    2428
2009    2430
2010    2430
2011    2429
2012    2430
2013    2431
2014    2430
2015    2429
2016    2428
2017    2430
2018    2431
2019    2429
2020     898
2021    2429
2022    2430
Name: season, dtype: int64

In [7]:
hv_mean = df.home_victory.mean()
hv_mean

0.5373320466186623

In [8]:
df.run_diff.value_counts()

 1     11537
-1      7501
 2      6259
-2      5965
 3      4967
-3      4713
 4      3886
-4      3795
 5      2810
-5      2800
 6      2132
-6      2021
 7      1487
-7      1468
 8      1106
-8       975
 9       745
-9       690
 10      471
-10      465
 11      303
-11      277
 12      187
-12      168
-13      138
 13      124
 14       71
-14       70
 15       41
-15       37
-16       32
 16       26
 17       14
 0        12
-17       11
-18       10
 19        8
 18        8
-19        6
 21        6
-21        4
 20        3
-20        2
 22        1
-22        1
-27        1
-23        1
Name: run_diff, dtype: int64

In [9]:
df.outs_total.value_counts()

51     30597
54     28188
60      1323
53      1250
52      1134
       ...
105        2
132        1
99         1
55         1
35         1
Name: outs_total, Length: 70, dtype: int64

In [10]:
df.home_victory[df.outs_total==53].mean()

0.9992

In [11]:
df.loc[(df.outs_total==53) & (df.home_victory!=1)]

,date,dblheader_code,day_of_week,team_v,league_v,game_no_v,team_h,league_h,game_no_h,runs_v,...,SLG_30_h,SLG_30_v,OBS_30_h,OBS_30_v,SB_30_h,SB_30_v,CS_30_h,CS_30_v,ERR_30_h,ERR_30_v
27337,20050915,0,Thu,SLN,NL,148,CHN,NL,147,6,...,0.444444,0.39569,0.766795,0.723061,12.0,20.0,6.0,5.0,15.0,23.0

In [12]:
df.game_no_h.value_counts().sort_index()

1      430
2      430
3      434
4      429
5      426
      ...
159    375
160    389
161    388
162    362
163     13
Name: game_no_h, Length: 163, dtype: int64

In [13]:
df[['OBP_162_h','OBP_162_v', 'SLG_162_h','SLG_162_v']].isna().sum()

OBP_162_h    2675
OBP_162_v    2671
SLG_162_h    2675
SLG_162_v    2671
dtype: int64

In [14]:
df = df.dropna(subset=['OBP_162_h', 'OBP_162_v', 'SLG_162_h', 'SLG_162_v'])

In [15]:
df.isna().sum()

date              0
dblheader_code    0
day_of_week       0
team_v            0
league_v          0
                 ..
SB_30_v           0
CS_30_h           0
CS_30_v           0
ERR_30_h          0
ERR_30_v          0
Length: 194, dtype: int64

In [16]:
df.dropna(subset=['OBP_162_h','OBP_162_v',
            'SLG_162_h','SLG_162_v', 
            # 'OBP_30_h','OBP_30_v',
            # 'SLG_30_h','SLG_30_v',
            # 'game_no_h',
           ])

,date,dblheader_code,day_of_week,team_v,league_v,game_no_v,team_h,league_h,game_no_h,runs_v,...,SLG_30_h,SLG_30_v,OBS_30_h,OBS_30_v,SB_30_h,SB_30_v,CS_30_h,CS_30_v,ERR_30_h,ERR_30_v
2245,19950616,0,Fri,SFN,NL,48,SLN,NL,48,5,...,0.388074,0.374275,0.708254,0.673735,16.0,33.0,8.0,12.0,22.0,28.0
2259,19950617,0,Sat,SFN,NL,49,SLN,NL,49,4,...,0.390148,0.378378,0.712028,0.680975,17.0,33.0,7.0,12.0,24.0,28.0
2268,19950618,0,Sun,MON,NL,50,CIN,NL,48,7,...,0.436941,0.387695,0.785737,0.712428,46.0,27.0,11.0,10.0,18.0,17.0
2269,19950618,0,Sun,ATL,NL,49,COL,NL,49,9,...,0.458984,0.440276,0.796798,0.779244,23.0,16.0,16.0,11.0,22.0,19.0
2271,19950618,0,Sun,FLO,NL,48,PHI,NL,48,3,...,0.355131,0.373412,0.690266,0.694399,11.0,16.0,7.0,12.0,23.0,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67350,20221005,0,Wed,KCA,AL,162,CLE,AL,162,2,...,0.396617,0.380435,0.720988,0.683631,36.0,19.0,6.0,10.0,21.0,10.0
67351,20221005,0,Wed,PHI,NL,162,HOU,AL,162,2,...,0.426036,0.431275,0.737570,0.746681,19.0,19.0,5.0,8.0,12.0,11.0
67352,20221005,0,Wed,ANA,AL,162,OAK,AL,162,2,...,0.354354,0.427734,0.634797,0.735567,10.0,11.0,2.0,2.0,17.0,17.0
67353,20221005,0,Wed,DET,AL,162,SEA,AL,162,4,...,0.398374,0.394685,0.708220,0.684473,15.0,8.0,6.0,4.0,21.0,16.0
67354,20221005,0,Wed,NYA,AL,162,TEX,AL,162,2,...,0.367781,0.435259,0.630340,0.762938,24.0,23.0,11.0,6.0,16.0,15.0

# Model

In [17]:
#Drop empates
df = df[df.run_diff!=0]

In [18]:
df_train = df[(df.season>1995) & (df.season<=2020)]
#df_valid = df[(df.season>=2019) & (df.season<=2020)]
df_test = df[df.season>=2021]

In [19]:
X = ['OBP_162_h','OBP_162_v',
            'SLG_162_h','SLG_162_v', 
             'OBP_30_h','OBP_30_v',
             #'SLG_30_h','SLG_30_v',
           ]
target = 'home_victory'

In [20]:
X

['OBP_162_h', 'OBP_162_v', 'SLG_162_h', 'SLG_162_v', 'OBP_30_h', 'OBP_30_v']

In [21]:
X_train = df_train.loc[:,X]
X_test = df_test.loc[:,X]

y_train = df_train[target].to_numpy()
y_test = df_test[target].to_numpy()

In [22]:
X_train.shape, X_test.shape #X_valid.shape,

((58059, 6), (4859, 6))

In [23]:
y_train.shape, y_test.shape #y_valid.shape

((58059,), (4859,))

In [24]:
X_train.isna().sum()

OBP_162_h    0
OBP_162_v    0
SLG_162_h    0
SLG_162_v    0
OBP_30_h     0
OBP_30_v     0
dtype: int64

In [25]:
smote = SMOTE()

In [26]:
X_train_sm, y_train_sm = smote.fit_resample(X_train.to_numpy(), y_train)

In [27]:
X_train_sm

array([[0.34452154, 0.35479778, 0.44599179, 0.42715525, 0.34916447,
        0.32446809],
       [0.34019783, 0.32868624, 0.41456483, 0.40930744, 0.35762712,
        0.2749301 ],
       [0.3359426 , 0.32851173, 0.41391809, 0.41072689, 0.33508772,
        0.2995671 ],
       ...,
       [0.33591543, 0.30708325, 0.43395241, 0.37799523, 0.31713849,
        0.29933093],
       [0.3429075 , 0.32202441, 0.43729634, 0.43846115, 0.35388748,
        0.32466606],
       [0.33725631, 0.32445235, 0.41345827, 0.421933  , 0.34537048,
        0.31294777]])

In [28]:
forest = RandomForestClassifier()

In [29]:
forest.fit(X_train_sm, y_train_sm)

RandomForestClassifier()

In [30]:
forest.score(X_train_sm,y_train_sm)

1.0

In [31]:
forest.score(X_test.to_numpy(),y_test)

0.537353364889895

In [32]:
y_test

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [39]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [40]:
y_pred = model.predict(X_test)

In [41]:
y_pred

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [44]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.5540234616176168